# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TmpSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='tmp')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
