# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import skd_crop.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=skd_crop.fields.SKDThumbnailerImageModelField(upload_to='avatars'),
        ),
    ]
