# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 13:04
from __future__ import unicode_literals

from django.db import migrations
import skd_crop.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userpic',
            field=skd_crop.models.SKDImageField(help_text='This is help text from field.', image_field='userpic_img', max_length=5000, parameters={'userpic_custom_crop': {'size': '224x224', 'title': 'Custom cropped Userpic'}, 'userpic_error_ratio': {'ratio': '3:1', 'size': '228x228', 'title': 'Large Userpic'}, 'userpic_l': {'ratio': '1:1', 'size': '512x512', 'title': 'Large Userpic'}, 'userpic_s': {'ratio': '3:1', 'size': 'x224', 'title': 'Small Userpic'}}, verbose_name='userpic'),
        ),
    ]
